### ISSUE TITLE
Subscribed channel missing 

### ISSUE THREAD

**Issue by IQ-Flex** [Shra1V32/TataSky-Playlist-AutoUpdater#12]
Hi I have subscribed for 385 channels but script showing only 353 channel.  not sure if i missed any step? Thanks

**Comment by Shra1V32** [comment]
Are your subscribed channels are listed here: https://gist.githubusercontent.com/Shra1V32/92cc6f8bbe3f4644d23fcde14ac799e2/raw/allchannels.txt

**Comment by IQ-Flex** [comment]
Yes, i am specifically looking for &Flix and Sony Pix HD. I also observed that non of the English language subscribed channel are appearing in m3u channel playlist.

**Comment by Shra1V32** [comment]
Maybe run the script again with option 1

**Comment by Shra1V32** [comment]
Closing the issue
