### ISSUE TITLE
not auto updating

### ISSUE THREAD

**Issue by pardhubharadhwaz** [Shra1V32/TataSky-Playlist-AutoUpdater#13]
though the URL is copied and pasted.. as usual the tv is playing for only exactly 24 hours from the min of generating a URL. after that drm exception error occurred.  Can u please let me know where I went wrong or code...?

**Comment by Shra1V32** [comment]
Looks like you're a Tivimate user, Which version of Tivimate are you using?

**Comment by pardhubharadhwaz** [comment]
> Looks like you're a Tivimate user, Which version of Tivimate are you using?

Tivimate version 2.8.0

**Comment by pardhubharadhwaz** [comment]
> Looks like you're a Tivimate user, Which version of Tivimate are you using?

Tivimate 2.8.0

**Comment by Shra1V32** [comment]
Using Mod apps?

**Comment by pardhubharadhwaz** [comment]
yes

**Comment by Shra1V32** [comment]
More likely yes, You are. Use the latest Tivimate version.

**Comment by pardhubharadhwaz** [comment]
okay.. will the problem get resolved?

**Comment by pardhubharadhwaz** [comment]
as I can see in git repository the workflow is updating succesfully.. but the changes are reflected as yesterday only.

**Comment by Shra1V32** [comment]
Closing this issue as you're using a mod app which isn't intended to help. Using other Apps like OTT Navigator/Latest version of Tivimate will definitely solve the issue. Some older versions of Tivimate has this issue where playlists don't get updated.

**Comment by pardhubharadhwaz** [comment]
Thank you so much Shravan
It resolved my issue. Thanks for the effort

**Comment by Shra1V32** [comment]
Consider donating to keep supporting/motivating 😄
