### ISSUE TITLE
Channels List

### ISSUE THREAD

**Issue by iamlegend-ui** [Shra1V32/TataSky-Playlist-AutoUpdater#14]
Bro why I am getting only 300 channels? In allChannels.json there are more than 500 channels. Please help me with this.

**Comment by Shra1V32** [comment]
You'll get subscribed channels only

**Comment by iamlegend-ui** [comment]
My TataSky account is deactivated bro, but 300 channels working fine

**Comment by Shra1V32** [comment]
All of them are FTA channels afaik
