### ISSUE TITLE
Could not generate Jwt token 

### ISSUE THREAD

**Issue by pardhubharadhwaz** [Shra1V32/TataSky-Playlist-AutoUpdater#15]
I'm unable to update my playlist and issue arises from yesterday.
![Screenshot_2022-06-30-19-06-26-629_com termux](https://user-images.githubusercontent.com/89439012/176691525-a707a9a0-dca7-4881-8f70-b7d96e95b7f6.jpg)

**Comment by Shra1V32** [comment]
Known issue, Fix is on the way.

**Comment by pardhubharadhwaz** [comment]
Okay... Waiting for the fix Shravan
