### ISSUE TITLE
not working on ott navigator

### ISSUE THREAD

**Issue by baadshah0786** [Shra1V32/TataSky-Playlist-AutoUpdater#16]
Plz fix not working on ott navigator app

**Comment by Shra1V32** [comment]
Are you sure that you've changed the Playlist-mode option?

**Comment by Activa4401** [comment]
Hi, workflow fail error. Please help

**Comment by Shra1V32** [comment]
Join the telegram group & report the issue there.

**Comment by Shra1V32** [comment]
No response from the user
