### ISSUE TITLE
edited something 

### ISSUE THREAD

**Issue by baadshah0786** [Shra1V32/TataSky-Playlist-AutoUpdater#18]
Bro can i edit the script for personal access and uses

**Comment by Shra1V32** [comment]
Open source means the same.

**Comment by baadshah0786** [comment]
bro i edit the script when i run the   root@Dell-Laptop:~# bash <(curl -s 'https://raw.githubusercontent.com/Mobassar4u/Tata-Play-IPTV-Autoupdater/main/curl.sh')

Cloning into 'Tata-Play-IPTV-Autoupdater'...
remote: Enumerating objects: 147, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 147 (delta 12), reused 0 (delta 0), pack-reused 120
Receiving objects: 100% (147/147), 68.32 KiB | 999.00 KiB/s, done.
Resolving deltas: 100% (82/82), done.
/dev/fd/63: line 15: ./main.sh: Permission denied

**Comment by Shra1V32** [comment]
`chmod 755 main.sh` then run the script using `./main.sh`
