### ISSUE TITLE
Support in OTT Navigator App

### ISSUE THREAD

**Issue by baadshah0786** [Shra1V32/TataSky-Playlist-AutoUpdater#20]
bro plz suport ott navigator app in your old script 
[Tata-Play-IPTV-AutoUpdater-1-main org.zip](https://github.com/Shra1V32/TataSky-Playlist-AutoUpdater/files/9348728/Tata-Play-IPTV-AutoUpdater-1-main.org.zip)
i m attaching my script plz make it ott navigator support 
humble request to you bro

**Comment by Shra1V32** [comment]
OTT Navigator support is already present in the script.

**Comment by baadshah0786** [comment]
> OTT Navigator support is already present in my script.

Bro i m attached script the script ott navigator app not supported

**Comment by Shra1V32** [comment]
If you want to modify the script, You can run & then edit your private repo. I'm not going to apply my brain for that again.
