### ISSUE TITLE
KODI Playback error

### ISSUE THREAD

**Issue by siddhusubbu** [Shra1V32/TataSky-Playlist-AutoUpdater#22]
Widevine Licence URL is very long, Is it possible to shorten it? KODI is not able to play with the long Licence URL.

**Comment by Shra1V32** [comment]
Okay, Which Platform of Kodi?

**Comment by siddhusubbu** [comment]
Windows Kodi Version 19.3 & 19.4 Matrix. Android Version Works Perfectly.

**Comment by Shra1V32** [comment]
Then you should raise the issue at Kodi's GitHub. 

https://github.com/xbmc/inputstream.adaptive/issues
