### ISSUE TITLE
Script isn't checking for TPlay Token Expiry

### ISSUE THREAD

**Issue by pardhubharadhwaz** [Shra1V32/TataSky-Playlist-AutoUpdater#24]
Hey Shravan, 
I'm very happy with your work. My url was expired yesterday and I'm unable to renew it and also even after deleting my playlist completely and building new repo doesn't solve the issue. Channels are not playing either in tivimate nor Kodi.
Playback issue and unable to play channels after the expiry date.

**Comment by Shra1V32** [comment]
Have you logged in again?

**Comment by pardhubharadhwaz** [comment]
In termux?

**Comment by Shra1V32** [comment]
Yes

**Comment by pardhubharadhwaz** [comment]
Nope.. it's already logged in

**Comment by Shra1V32** [comment]
You need to login again!

**Comment by pardhubharadhwaz** [comment]
Okay thank you shravan

**Comment by Shra1V32** [comment]
Great use case, Will implement that check in script

**Comment by pardhubharadhwaz** [comment]
Okay shravan

**Comment by pardhubharadhwaz** [comment]
Tried logging in again... It worked

**Comment by Shra1V32** [comment]
Aaaaaand Finally fixed!

**Comment by chetancable** [comment]
How to check expiry date of m3u url

**Comment by chetancable** [comment]
Pls guide me to check expiry date of my m3u url of tataplay
