### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by drtiwarir** [Shra1V32/TataSky-Playlist-AutoUpdater#25]
I am unable to generate links for Kodi getting message 
./main.sh: line 71: [[: :1663748638: syntax error: operand expected (error token is ":1663748638")

Have look below for details

LOGIN STATUS   : True
SUBSCRIBER ID  : **********
Playlist Expiry: Tue 20 Dec 2022 01:49:59 PM IST
Playlist Type  : Kodi | Tivimate
Author         : https://github.com/Shra1V32

./main.sh: line 71: [[: :1663748401: syntax error: operand expected (error token is ":1663748401")
Main Menu

1) Login using RMN & OTP
2) Change Playlist Type
3) Manage my M3U playlists
4) Build my Auto Updater
5) Logout
6) Exit
 
Make your selection: 

LOGIN STATUS   : True
SUBSCRIBER ID  : **********
Playlist Expiry: Tue 20 Dec 2022 01:49:59 PM IST
Playlist Type  : Kodi | Tivimate
Author         : https://github.com/Shra1V32

./main.sh: line 71: [[: :1663748625: syntax error: operand expected (error token is ":1663748625")
[◆] You've chosen Change Playlist Type

Which type of playlist would you like to have? (Both are Tivimate compatible)

  1. Kodi-Compatible
  2. OTT-Navigator-Compatible

Select from the options above: [◆] Option 1 chosen

LOGIN STATUS   : True
SUBSCRIBER ID  : **********
Playlist Expiry: Tue 20 Dec 2022 01:49:59 PM IST
Playlist Type  : Kodi | Tivimate
Author         : https://github.com/Shra1V32

./main.sh: line 71: [[: :1663748638: syntax error: operand expected (error token is ":1663748638")
Main Menu

1) Login using RMN & OTP
2) Change Playlist Type
3) Manage my M3U playlists
4) Build my Auto Updater
5) Logout
6) Exit

**Comment by drtiwarir** [comment]
I am using the script on Ubuntu 20.04
Please help me generate links for Kodi.
Thanks

**Comment by Shra1V32** [comment]
Is it fine now, Or still facing the issue as of now? I've tested it & it works fine :/

**Comment by drtiwarir** [comment]
It's working in Tivimate (m3u) link, but Kodi repository is not working, it doesn't download (can't download zip file)
Can we fix this ?
Do I have to refresh this everyday or you have done something like a cron job ?
Thanks

**Comment by Shra1V32** [comment]
Contact from: https://t.me/tskyiptv

**Comment by drtiwarir** [comment]
I am sorry bro, I don't use telegram
Any other way ?

**Comment by drtiwarir** [comment]
Just joined on my phone
