### ISSUE TITLE
Data not updated.

### ISSUE THREAD

**Issue by sneha2310** [Shra1V32/TataSky-Playlist-AutoUpdater#27]
Your data is not update in the mentioned linked. https://kong-tatasky.videoready.tv/content-detail/pub/api/v1/channels?limit=443

**Comment by Shra1V32** [comment]
It is updated for every 24Hrs

**Comment by sneha2310** [comment]
This is the updated link above one is expired.
 https://kongtatasky.videoready.tv/portalsearch/pub/api/v1/channels/scheduledate=&languageFilters=&genreFilters=&limit=772&offset=60&total_count

**Comment by sneha2310** [comment]
Thanks for the response. I figured out my issue. The code is nice.

**Comment by Shra1V32** [comment]
Thanks, The link sent above doesn't seem to work.
