### ISSUE TITLE
Something went wrong while pushing

### ISSUE THREAD

**Issue by mrblade** [Shra1V32/TataSky-Playlist-AutoUpdater#28]
It used to work fine but I noticed in the morning that the m3u file did not have widevine url. I installed the entire script again, logged in with a new github token and tried to build the auto updater with option'5'. It fails in the end saying Something went wrong while pushing.
![image](https://user-images.githubusercontent.com/9509855/203695282-32cfc030-46d3-4450-be52-772d71587e0b.png)

**Comment by Shra1V32** [comment]
Try deleting the whole repo & then try again
