### ISSUE TITLE
Channel not working

### ISSUE THREAD

**Issue by drtiwarir** [Shra1V32/TataSky-Playlist-AutoUpdater#30]
I am running it in Kodi
Working well, but since couple of weeks Sony BBC Earth HD doesn't play 
Can you please fix it.

Regards

**Comment by Shra1V32** [comment]
Source issue, Script has nothing to do with it.

**Comment by drtiwarir** [comment]
Zee cinema HD &  Sony BBC Earth HD doesn't play, other channels are working well, can you please check the links, seems some error with links rather than source.
Because both mentioned channels are working in Jiotv (BotAllen repo)
I have tried in Kodi & Tivimate.
Regards

**Comment by drtiwarir** [comment]
Working today, thanks for fixing it
