### ISSUE TITLE
Issues in Debian 12 due to PEP 668

### ISSUE THREAD

**Issue by kartikguha** [Shra1V32/TataSky-Playlist-AutoUpdater#31]
Getting following error on Debian 12

----------------------------------------------------------------------------
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.
----------------------------------------------------------------------------

**Comment by Shra1V32** [comment]
Platform not supported (or) Simply use Google Cloud Shell
