### ISSUE TITLE
Failed to connect to local host 

### ISSUE THREAD

**Issue by K-VIJAYARAJAN** [Shra1V32/TataSky-Playlist-AutoUpdater#35]
Work flow shows the following error
![image](https://github.com/Shra1V32/TataSky-Playlist-AutoUpdater/assets/92156623/56937881-2d56-4fa8-a6e8-ea60ff96ea8b)

**Comment by Shra1V32** [comment]
Sync the repo using option 1 in manage my playlist

**Comment by K-VIJAYARAJAN** [comment]
Tried sync too before analyzing work flow. API rate limit exceeded. So issue stands unresolved
