### ISSUE TITLE
not working through password 

### ISSUE THREAD

**Issue by Maroof4u** [Shra1V32/TataSky-Playlist-AutoUpdater#5]
Plz fix it not working through password
Say login false try with rmn and otp

**Comment by Shra1V32** [comment]
Check Telegram

**Comment by Shra1V32** [comment]
The login option with Password from Tata Sky has been deprecated, Soon I'll release a fix for it. Till then keep using https://github.com/ForceGT/Tata-Sky-IPTV

**Comment by Shra1V32** [comment]
Try nd lemme know now
