### ISSUE TITLE
where we can get tatasky m3u list? i have generated m3u

### ISSUE THREAD

**Issue by masey0** [Shra1V32/TataSky-Playlist-AutoUpdater#8]
where we can get m3u list? i have generated m3u

**Comment by Shra1V32** [comment]
Script already prints out the playlist url

**Comment by masey0** [comment]
![Screenshot_20220405_223302_com termux](https://user-images.githubusercontent.com/102936457/161811054-e1341d2e-a2f3-4dbe-b348-5011b7cb8f18.jpg)

**Comment by masey0** [comment]
It is not printing
